---
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: echo ${nextRelease.version} > version.txt
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - version.txt
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - "@semantic-release/github"
