---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptime-kuma

resources:
  - https://github.com/adborden/k8s-uptime-kuma.git/uptime-kuma?ref=1.0.0

images:
  - name: louislam/uptime-kuma
    newTag: 2.0.2
